/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddFeedbackDialog: typeof import('./src/components/Dialogs/AddFeedbackDialog.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar/AppToolbar.vue')['default']
    EditFeedbackDialog: typeof import('./src/components/Dialogs/EditFeedbackDialog.vue')['default']
    FeedbackDialog: typeof import('./src/components/FeedbackDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
