/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddFeedback: typeof import('./src/components/Dialogs/AddFeedback.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar/AppToolbar.vue')['default']
    EditFeedback: typeof import('./src/components/Dialogs/EditFeedback.vue')['default']
    EmptyFeedbackComponent: typeof import('./src/components/Feedback/EmptyFeedbackComponent.vue')['default']
    FeedbackCard: typeof import('./src/components/FeedbackCard/FeedbackCard.vue')['default']
    FrontendMentorBox: typeof import('./src/components/FrontendMentorBox/FrontendMentorBox.vue')['default']
    GoBackButton: typeof import('./src/components/GoBackButton/GoBackButton.vue')['default']
    LandingPageBlog: typeof import('./src/components/LandingPageBlog/LandingPageBlog.vue')['default']
    LandingPageFeatures: typeof import('./src/components/LandingPageFeatures/LandingPageFeatures.vue')['default']
    LandingPageFooter: typeof import('./src/components/LandingPageFooter/LandingPageFooter.vue')['default']
    LandingPageHeadline: typeof import('./src/components/LandingPageHeadline/LandingPageHeadline.vue')['default']
    LandingPageNavbar: typeof import('./src/components/LandingPageNavbar/LandingPageNavbar.vue')['default']
    LandingPageOverview: typeof import('./src/components/LandingPageOverview/LandingPageOverview.vue')['default']
    LandingPageTrustedBy: typeof import('./src/components/LandingPageTrustedBy/LandingPageTrustedBy.vue')['default']
    LoaderOverlay: typeof import('./src/components/LoaderOverlay/LoaderOverlay.vue')['default']
    LogIn: typeof import('./src/components/Auth/LogIn.vue')['default']
    RoadmapBox: typeof import('./src/components/RoadmapBox/RoadmapBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/Auth/SignUp.vue')['default']
    SortingPanel: typeof import('./src/components/SortingPanel/SortingPanel.vue')['default']
    Tag: typeof import('./src/components/Tag/Tag.vue')['default']
    TagsBox: typeof import('./src/components/TagsBox/TagsBox.vue')['default']
  }
}
