version: '3'
services:
 app:
 build:
 context: .
 dockerfile: Dockerfile
 container_name: feedback-app
 ports:
 - 8080:80
nginx:
 image: nginx:alpine
 container_name: nginx-app
 volumes:
 - ./default.conf:/etc/nginx/conf.d/default.conf
 ports:
 - 80:80
 depends_on:
 - app