/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddFeedback: typeof import('./../components/Dialogs/AddFeedback.vue')['default']
    AppToolbar: typeof import('./../components/AppToolbar/AppToolbar.vue')['default']
    AvatarMenu: typeof import('./../components/AvatarMenu/AvatarMenu.vue')['default']
    CommentCard: typeof import('./../components/CommentCard/CommentCard.vue')['default']
    EditAccount: typeof import('./../components/EditAccount/EditAccount.vue')['default']
    EditFeedback: typeof import('./../components/Dialogs/EditFeedback.vue')['default']
    EmptyFeedback: typeof import('./../components/EmptyFeedback/EmptyFeedback.vue')['default']
    FeedbackBar: typeof import('./../components/FeedbackBar/FeedbackBar.vue')['default']
    FeedbackCard: typeof import('./../components/FeedbackCard/FeedbackCard.vue')['default']
    FrontendMentorBox: typeof import('./../components/FrontendMentorBox/FrontendMentorBox.vue')['default']
    GoBackButton: typeof import('./../components/GoBackButton/GoBackButton.vue')['default']
    LandingPageBlog: typeof import('./../components/LandingPageBlog/LandingPageBlog.vue')['default']
    LandingPageFeatures: typeof import('./../components/LandingPageFeatures/LandingPageFeatures.vue')['default']
    LandingPageFooter: typeof import('./../components/LandingPageFooter/LandingPageFooter.vue')['default']
    LandingPageHeadline: typeof import('./../components/LandingPageHeadline/LandingPageHeadline.vue')['default']
    LandingPageNavbar: typeof import('./../components/LandingPageNavbar/LandingPageNavbar.vue')['default']
    LandingPageOverview: typeof import('./../components/LandingPageOverview/LandingPageOverview.vue')['default']
    LandingPageTrustedBy: typeof import('./../components/LandingPageTrustedBy/LandingPageTrustedBy.vue')['default']
    LoaderOverlay: typeof import('./../components/LoaderOverlay/LoaderOverlay.vue')['default']
    LogIn: typeof import('./../components/Auth/LogIn.vue')['default']
    ReplyCard: typeof import('./../components/ReplyCard/ReplyCard.vue')['default']
    RoadmapBox: typeof import('./../components/RoadmapBox/RoadmapBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./../components/Auth/SignUp.vue')['default']
    SortingPanel: typeof import('./../components/SortingPanel/SortingPanel.vue')['default']
    Tag: typeof import('./../components/Tag/Tag.vue')['default']
    TagsBox: typeof import('./../components/TagsBox/TagsBox.vue')['default']
    VotersCard: typeof import('./../components/VotersCard/VotersCard.vue')['default']
  }
}
